# .ruff.toml (legacy / root-level schema)

# Max line length
line-length = 100

# Files & dirs to ignore entirely
exclude = [
  "*.ipynb",      # Jupyter notebooks
  ".venv",        # virtual env
  ".git",         # git metadata
  "optimize/*.ipynb",
  "scripts/*.ipynb",
]

# Codes to ignore everywhere
ignore = [
  "E402",  # import not at top
  "E701",  # multiple statements on one line
  "E702",
  "E722",  # bare except
  "F401",  # unused import
  "F821",  # undefined name
]

# Formatter options
[format]
quote-style = "double"
