# .ruff.toml  (root-level, tanpa [tool.ruff])

# -- umum -----------------------------------------------------------------
line-length = 100
extend-exclude = [ "*.ipynb" ]   # abaikan semua notebook

# -- lint rules -----------------------------------------------------------
[lint]
ignore = [
  "E402",  # import not at top (biasa di notebook)
  "E701", "E702",  # multiple statements / same line
  "E722",          # bare except
  "F401",          # unused import
  "F821"           # undefined name
]
fixable = "all"

# (opsional) formatter behaviour
[format]
quote-style = "double"
