# fly.toml app configuration file generated for traffic-sign-api-divine-wildflower-1952 on 2025-06-28T16:11:09+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'traffic-sign-api-divine-wildflower-1952'
primary_region = 'sin'

[build]
  image = 'ghcr.io/helios190/traffic_sign_classification-main:latest'

[registry]
  username = "${REGISTRY_USERNAME}"
  password = "${REGISTRY_PASSWORD}"
  
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
