app = 'traffic-sign
primary_region = 'sin'

[build]
  image = 'ghcr.io/helios190/traffic_sign_classification-main:latest'

[env]
  ARTEFACT_PATH = 'Traffic.h5'
  PYTHONUNBUFFERED = '1'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
