# .github/workflows/ci-docker.yml
name: CI · lint · test · docker

on:
  pull_request:
  push:
    branches: [ main ]

env:
  IMAGE: ghcr.io/${{ github.repository }}

# ───── 1) Lint job ───────────────────────────────────────────
# snippet — only the lint job part
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.11"}

      - name: Install Ruff
        run: python -m pip install --quiet ruff


# ───── 2) Test job (needs lint) ──────────────────────────────
  test:
    needs: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: >-
            pip-${{ hashFiles('requirements.txt') }}-${{ runner.os }}-${{
            github.run_id }}
      - name: Install deps & pytest
        run: |
          python -m pip install --quiet -r requirements.txt pytest
      - name: Run tests
        run: pytest -q

# ───── 3) Build & push Docker (only on main) ────────────────
  docker:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ github.sha }}
            ${{ env.IMAGE }}:latest
          cache-from: type=gha
          cache-to:   type=gha,mode=max
