# .github/workflows/ci-docker.yml
name: CI · lint · test · docker

on:
  pull_request:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io

# ───── 1) Lint job ───────────────────────────────────────────
# snippet — only the lint job part
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.11"}

      - name: Install Ruff
        run: python -m pip install --quiet ruff


# ───── 2) Test job (needs lint) ──────────────────────────────
  test:
    needs: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: >-
            pip-${{ hashFiles('requirements.txt') }}-${{ runner.os }}-${{
            github.run_id }}
      - name: Install deps & pytest
        run: |
          python -m pip install --quiet -r requirements.txt pytest
      - name: Run tests
        run: pytest -q

# ───── 3) BUILD & PUSH DOCKER (hanya di main) ───────────────
  docker:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      # ▸ builder qemu + buildx → enable multi-arch
      - uses: docker/setup-qemu-action@v3          # emulasi arm64 di runner x86
      - uses: docker/setup-buildx-action@v3

      # ▸ login ke GHCR (pakai secret GHCR_TOKEN atau GITHUB_TOKEN)
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN || secrets.GITHUB_TOKEN }}

      # ▸ nama repo lower-case
      - id: prep
        run: echo "repo=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

      # ▸ build + push manifest linux/amd64 & linux/arm64
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64          # ★ multi-arch
          tags: |
            ${{ env.REGISTRY }}/${{ steps.prep.outputs.repo }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ steps.prep.outputs.repo }}:latest
          cache-from: type=gha
          cache-to:   type=gha,mode=max