name: CI – lint · test · docker

on:
  pull_request:
  push:
    branches: [ main ]

env:
  IMAGE: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write        # ← untuk push ke GHCR
    steps:
    - uses: actions/checkout@v4

    # ----- Python env + cache -----
    - uses: actions/setup-python@v5
      with: { python-version: '3.11' }
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: pip-${{ hashFiles('requirements.txt') }}

    # ----- lint -----
    - run: |
        pip install ruff
        ruff check .

    # ----- unit-test -----
    - run: |
        pip install -r requirements.txt pytest
        pytest -q

    # ----- login & build/push image (push hanya di main) -----
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        tags: |
          ${{ env.IMAGE }}:${{ github.sha }}
          ${{ env.IMAGE }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
