name: Deploy 路 fly

on:
  workflow_run:
    workflows: ["CI 路 lint 路 test 路 docker"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy \
            --traffic-sign-api \
            --image ghcr.io/${{ github.repository }}:latest \
            --config fly.toml
