name: Deploy to Fly

on:
  workflow_run:
    workflows: [ "CI · lint · test · docker" ]
    types: [ completed ]
    branches: [ main ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@v1
      - run: flyctl deploy --app traffic-sign-api --image ghcr.io/${{ github.repository }}:latest
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}